#指定定时执行的cron表达式
# 工作日执行
robot:
  schedule:
    # 每30分钟执行一次
    cron: 0 0/30 * * * ?
    # 下午9点整执行一次
    cron1: 0 0 21 * * ?
    # 从下午9点开始每5分钟执行一次
    cron2: 0 0/5 21 * * ?
    # 每6个小时执行一次
    cron3: 0 0 0-6 * * ?
    # 早上8点整执行一次
    cron4: 0 0 8 * * ?

# 账号信息


#项目文件路径
project:
  base:
    path: C:/dev/env/browerDriver/


#服务端口号
server:
  port: 8080
